### ISSUE TITLE
Unknown Error on package installation

### ISSUE THREAD

**Issue by ambrumyan** [jonschlinkert/read-yaml#3]
Below is error trace

npm ERR! Error: UNKNOWN, symlink '../esprima/bin/esparse.js'
npm ERR! If you need help, you may report this *entire* log,
npm ERR! including the npm and node versions, at:
npm ERR!     <http://github.com/npm/npm/issues>

npm ERR! System Linux 3.13.0-46-generic
npm ERR! command "/usr/bin/node" "/usr/bin/npm" "install"
npm ERR! cwd /var/www
npm ERR! node -v v0.10.34
npm ERR! npm -v 1.4.28
npm ERR! path ../esprima/bin/esparse.js
npm ERR! code UNKNOWN
npm ERR! errno -1
npm ERR! not ok code 0

**Comment by shinnn** [comment]
Using too old npm. Please update it and try again.

```js
npm install -g npm
```

**Comment by ambrumyan** [comment]
Thanks, I updated npm but now I have the following problem.


npm ERR! Linux 3.13.0-46-generic
npm ERR! argv "node" "/usr/bin/npm" "install"
npm ERR! node v0.10.34
npm ERR! npm  v2.7.0
npm ERR! path ../esprima/bin/esparse.js
npm ERR! code UNKNOWN
npm ERR! errno -1

npm ERR! UNKNOWN, symlink '../esprima/bin/esparse.js'
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <http://github.com/npm/npm/issues>
npm ERR! Linux 3.13.0-46-generic
npm ERR! argv "node" "/usr/bin/npm" "install"
npm ERR! node v0.10.34
npm ERR! npm  v2.7.0
npm ERR! path npm-debug.log.a815b9499fb7c4c3c98a7954f0462929
npm ERR! code ETXTBSY
npm ERR! errno 62

**Comment by shinnn** [comment]
I found you are doing multiposting to various repos and bother many OSS developers.

https://github.com/npm/npm/issues/7608
https://github.com/nodeca/js-yaml/issues/175

I don't want to support such a disrespectful user. Just what js-yaml author said. https://github.com/nodeca/js-yaml/issues/175#issuecomment-78455960

**Comment by ambrumyan** [comment]
if you make attention and read comments you will see that I didn't get help for my question . 
READ THEM CAREFULLY 

nodeca/js-yaml#175 Puzrin  , tells to aask NPM about that 
npm/npm#7608 this is question for NPM .

as I have problems for both backages read-yaml and js-yaml , I want to get response from both you and Puzin, I dont think that this is behavior of disrespectfull user, if you don't know solution you can wrote here about that :) and not put comments that are not related to issue.

Thanks

**Comment by jonschlinkert** [comment]
`npm cache clean` and update to the latest node.js or io.js
